name: Release App with Production

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-app-dev:
    name: Build App with production
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Setup Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'

    - name: Copy Repo Files
      uses: actions/checkout@v2

    - name: Build App
      env:
        NODE_ENV: production
      run: |
        printf "${{secrets.REACT_ENV_DEVELOPMENT}}" > ./.env.production
        yarn install --production=false
        yarn build:production

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        known_hosts: 'a'

    - name: Upload App
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_UPLOAD_PATH: ${{ secrets.REMOTE_UPLOAD_PATH }}
      run: |
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        ./scripts/upload.sh
