name: Release App with DEV

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-app-dev:
    name: Build App with development
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Setup Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'

    - name: Copy Repo Files
      uses: actions/checkout@v2

    - name: Build App
      env:
        NODE_ENV: development
      run: |
        printf "${{secrets.REACT_ENV_DEVELOPMENT}}" > ./.env.development
        yarn install --production=false
        yarn build:development

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        known_hosts: 'a'

    - name: Upload App
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_UPLOAD_PATH: ${{ secrets.DEV_REMOTE_UPLOAD_PATH }}
      run: |
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        ./scripts/upload.sh

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Telegram send success message
      if: ${{ success() }}
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        MESSAGE_TEXT: |
          ✅ 呵呵，相册测试服前端已经部署。
          版本: ${{ steps.package-version.outputs.current-version}}
          构建数: ${{ github.run_number }}
          Commit message: ${{ github.event.commits[0].message }}
      run: |
        ./scripts/tg-message.sh

    - name: Telegram send failure message
      if: ${{ failure() }}
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        MESSAGE_TEXT: |
          ❌ 呵呵，相册测试服前端部署失败。早该管管了。
          版本: ${{ steps.package-version.outputs.current-version}}
          构建数: ${{ github.run_number }}
          Commit message: ${{ github.event.commits[0].message }}
      run: |
        ./scripts/tg-message.sh
